version: '3.1'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    image: ma_super_app
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: mydb
    ports:
      - '3000:3000'
    depends_on:
      - db
    command: sh -c "while ! nc -z db 3306; do sleep 1; done; node src/index.js"

volumes:
  mysql_data:

